assetClasses = ["Debtors",
  "Inventory",
  "Livestock",
  "Member's interest",
  "Shares",
  "Investment portfolio",
  "Crops/Agricultural yields",
  "Machinery/Equipment",
  "Jewelry",
  "Trade credit insurance policy",
  "Loan account",
  "Futures",
  "Contracts",
  "Agreements",
  "Guarantees",
  "Sureties",
  "Other financial instrument"
];
